<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<testResult type="org.overture.typechecker.tests.external.ExternalModulesSlTypeCheckTest">
<message column="8" line="15" message="Statement will not be reached" messageType="warning" number="5006" resource="casesstmt-09.vdm"/>
<message column="8" line="16" message="Statement will not be reached" messageType="warning" number="5006" resource="casesstmt-09.vdm"/>
<message column="12" line="13" message="Definition 'c' not used" messageType="warning" number="5000" resource="casesstmt-09.vdm"/>
<message column="16" line="12" message="Definition 'b' not used" messageType="warning" number="5000" resource="casesstmt-09.vdm"/>
<message column="16" line="11" message="Definition 'a' not used" messageType="warning" number="5000" resource="casesstmt-09.vdm"/>
<message column="15" line="18" message="Statement will not be reached" messageType="warning" number="5006" resource="casesstmt-09.vdm"/>
<message column="5" line="11" message="Pattern cannot match" messageType="error" number="3311" resource="casesstmt-09.vdm"/>
<message column="8" line="14" message="Statement may return void value" messageType="error" number="3328" resource="casesstmt-09.vdm"/>
<message column="8" line="16" message="Value is not of the right type" messageType="error" number="3327" resource="casesstmt-09.vdm"/>
<message column="15" line="18" message="Statement may return void value" messageType="error" number="3328" resource="casesstmt-09.vdm"/>
<message column="1" line="8" message="Operation returns unexpected type" messageType="error" number="3027" resource="casesstmt-09.vdm"/>
<result/>
</testResult>
