<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<testResult type="org.overture.typechecker.tests.external.ExternalModulesSlTypeCheckTest">
<message column="13" line="35" message="Definition 'b' not used" messageType="warning" number="5000" resource="letstmt.vdm"/>
<message column="14" line="38" message="Definition 'arg2' not used" messageType="warning" number="5000" resource="letstmt.vdm"/>
<message column="9" line="79" message="a at 78:8 hidden by a" messageType="warning" number="5008" resource="letstmt.vdm"/>
<message column="13" line="81" message="a at 79:9 hidden by a" messageType="warning" number="5008" resource="letstmt.vdm"/>
<message column="18" line="82" message="a at 79:9 hidden by a" messageType="warning" number="5008" resource="letstmt.vdm"/>
<message column="13" line="85" message="a at 79:9 hidden by a" messageType="warning" number="5008" resource="letstmt.vdm"/>
<message column="13" line="85" message="Definition 'a' not used" messageType="warning" number="5000" resource="letstmt.vdm"/>
<message column="26" line="27" message="Value is not of the right type" messageType="error" number="3327" resource="letstmt.vdm"/>
<message column="19" line="27" message="Constructor field 2 is of wrong type" messageType="error" number="3129" resource="letstmt.vdm"/>
<message column="13" line="57" message="Name 'LetStmtTest`b' is not in scope" messageType="error" number="3182" resource="letstmt.vdm"/>
<message column="13" line="68" message="Name 'LetStmtTest`b' is not in scope" messageType="error" number="3182" resource="letstmt.vdm"/>
<message column="13" line="79" message="Name 'LetStmtTest`b' is not in scope" messageType="error" number="3182" resource="letstmt.vdm"/>
<result/>
</testResult>
